project: default
source:
  repoURL: https://github.com/Asmo-D/ArgoCDtraining
  path: K8sdeploy
  targetRevision: HEAD
destination:
  server: https://kubernetes.default.svc
  namespace: orano-demo
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true