apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-proj
  namespace: argocd
spec:
  description: "A sample demo project"
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - server: '*'
  sourceRepos:
  - '*'