apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-orano
  labels:
    app: nginx-orano
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-orano
  template:
    metadata:
      labels:
        app: nginx-orano
    spec:
      containers:
      - name: demo-ginx-container
        image: nginx_orano:1.0.0