apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-orano-ingress
  namespace: orano-demo
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: orano.$IP.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-orano-svc
                port:
                  number: 80